# version: '2.0'

services:
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: rick
      POSTGRES_PASSWORD: morty
      POSTGRES_DB: rickandmorty
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  node:
    image: node:22
    container_name: api
    working_dir: /app
    environment:
      DB_USER: rick
      DB_PASSWORD: morty
      DB_DATABASE: rickandmorty
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    entrypoint: /app/entrypoint.sh
    volumes:
      - ./api:/app/
    ports:
      - "3000:3000"
    restart: always
volumes:
  db_data: