services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    container_name: frontend
    volumes:
      - ./frontend/pickle-web:/app
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm start"
    depends_on:
      - node
      - redis
    restart: always
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: rick
      POSTGRES_PASSWORD: morty
      POSTGRES_DB: rickandmorty
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
  node:
    image: node:22
    container_name: api
    working_dir: /app
    environment:
      DB_USER: rick
      DB_PASSWORD: morty
      DB_DATABASE: rickandmorty
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - redis
    entrypoint: /app/entrypoint.sh
    volumes:
      - ./api:/app/
    ports:
      - "3001:3000"
    restart: always
volumes:
  db_data: